### ISSUE TITLE
Don't map `yd` for visual mode by default

### ISSUE THREAD

**Issue by chrisgrieser** [smjonas/duplicate.nvim#1]
the plugins seems to map `yd` for visual mode by default. While a visual mode duplication command is indeed useful, I think it should be at least a separate keymap, or something other than `yd`. 

The reason is that mapping `yd` to visual mode means that yanking in visual mode with `y` now has a small delay (`opt.timeout`), since vim is waiting to see whether the `d` is pressed, making yanks in visual mode quite annoying.

**Comment by smjonas** [comment]
Good point, I added `textobject_visual_mode` that's set to `nil` by default
