### ISSUE TITLE
After duplication, the cursor should be placed at the duplicated text, not the original

### ISSUE THREAD

**Issue by chrisgrieser** [smjonas/duplicate.nvim#7]
right now, after duplicating text, the cursor seems to be stick and staying up at the same position. 

However, usually after duplication you want to change the duplicated text, not the original text (for instance, in git diffs the duplicated text is indicated as modified). therefore, it would be more beneficial if the cursor would be moved to the duplicated text instead of being sticky.

**Comment by smjonas** [comment]
Good suggestion, right now this will move the cursor to the end of the yanked text though. Do you agree that it would be better if the cursor was moved to the first character of the duplicated text instead?

**Comment by chrisgrieser** [comment]
Yea!
